import { useTheme } from "@/hooks";
import { Colors } from "@/theme/Variables";
import { CloseButton, Eye, Play, Stars } from "@/theme/svg";
import { useState } from "react";
import {
  Dimensions,
  StyleSheet,
  Text,
  View,
  TouchableOpacity,
  ScrollView,
  Image,
  Modal,
  SafeAreaView,
} from "react-native";
import ActionSheet, {
  SheetManager,
  SheetProps,
} from "react-native-actions-sheet";
import LinearGradient from "react-native-linear-gradient";
import * as Progress from "react-native-progress";
import WebView from "react-native-webview";
const NewsSheet = (props: any) => {
  const { Fonts, Layout, Gutters, darkMode: isDark } = useTheme();
  const [scrollPosition, setScrollPosition] = useState(0);
  const [summaryView, setSummaryView] = useState(false);

  const handleScroll = (event: any) => {
    const offsetY = event.nativeEvent.contentOffset.y;
    const scrollHeight = event.nativeEvent.contentSize.height;
    const windowHeight = event.nativeEvent.layoutMeasurement.height;
    const progress = (offsetY / (scrollHeight - windowHeight)) * 100;
    setScrollPosition(progress);
  };
  const hideActionSheet = () => {
    SheetManager.hide("NewsSheet");
  };

  return (
    <ActionSheet id={props.sheetId}>
      <LinearGradient colors={["rgba(0,0,0,0)", "rgba(120,120,120,0.5)"]}>
        <SafeAreaView style={styles.container}>
          <View style={styles.header}>
            <View>
              <Text
                style={[Fonts.textRegular, Fonts.textWhite, Fonts.textBold]}
              >
                News
              </Text>
            </View>
            <View style={styles.iconContainer}>
              <TouchableOpacity style={[Gutters.smallRPadding]} onPress={()=>setSummaryView(!summaryView)}>
                <Stars />
              </TouchableOpacity>
              <TouchableOpacity onPress={hideActionSheet}>
                <CloseButton />
              </TouchableOpacity>
            </View>
          </View>
           <View style={[Gutters.tinyMargin,Layout.fill]}>
              {summaryView ? <View style={styles.AISummary}>
                <View style={styles.AIHeader}>
                    <Text style={styles.AICaption}>Summary</Text>
                </View>
                <View style={styles.AIParagraph}>
                  <Text style={styles.AIText}>
                    {props?.payload?.summary || ''}
                  </Text>
                </View>
                <View style={styles.AIFooter}>
                    <Text style={styles.AIFooterText}>Summary generated by AI.</Text> 
                </View>

              </View> :
              <WebView 
              source={{ uri: props?.payload?.linkUrl.toString() }} 
              style={{ flex: 1 }} 
              onScroll={handleScroll}
            />
            }
            </View>
          <View style={[Layout.row, Gutters.tinyMargin]}>
            <Progress.Bar
              progress={scrollPosition / 100}
              width={Dimensions.get("screen").width - 60}
              height={5}
              style={styles.progressBar}
              color={Colors.green}
              useNativeDriver={true}
            />
            <Eye style={[Gutters.smallBMargin]} />
          </View>
        </SafeAreaView>
      </LinearGradient>
    </ActionSheet>
  );
};
const styles = StyleSheet.create({
  container: {
    height: Dimensions.get("screen").height - 250,
    backgroundColor: "rgba(0,0,0,0.8)",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    height: 60,
  },
  iconContainer: {
    alignItems: "center",
    flexDirection: "row",
  },
  progressBar: {
    height: 5,
    marginBottom: 30,
    borderColor: "transparent",
    alignSelf: "center",
    marginEnd: 10,
  },
  AISummary: {
    paddingVertical:10,
    backgroundColor: 'black',
    borderRadius: 10,
  },
  AIHeader: {
    marginLeft: 10,
    marginTop: 10,
  },
  AIParagraph: {
    marginLeft: 10,
    marginTop: 10,
    marginRight: 5
  },
  AICaption: {
    fontSize: 24,
    color: 'white',
  },
  AIText: {
    color: 'white',
    fontSize: 14,
    marginRight: 5

  },
  AIFooter: {
    marginLeft: 10,
    marginTop: 20,
  },
  AIFooterText: {
    color: 'white',
    fontSize: 12
  }
});
export default NewsSheet;
