export { default as Startup } from './Startup/Startup';
export { default as Login } from './Login/Login'
export { default as Signup } from './Signup/Signup'
export { default as OtpScreen } from './OtpScreen/OtpScreen'
export { default as EditProfile } from './EditProfile/EditProfile'
export { default as ProfileScreen } from './ProfileScreen/ProfileScreen'
export { default as ForgotPassword } from './ForgotPassword/ForgotPassword'
export { default as ResetPassword } from './ResetPassword/ResetPassword'
export { default as ReferralScreen } from './ReferralScreen/ReferralScreen'
export { default as GetStartedScreen} from './GetStartedScreen/GetStartedScreen'
