

export const Constants = {
    getStarted : "Get Started" ,
    startByChoosing: "Start by choosing your role",
    login: "Login",
    keyboardType:{
        email: 'email-address',
        phone: 'number-pad',
        default: 'default'
    },
    email:'Email',
    password:'Password',
    emailAddress:'Username/email ID',
    fullName:"Full Name",
    phoneNo:'Phone Number',
    signin:'SIGN IN',
    forgotPassword:'Forgot password?',
    setUpAccount: "Setup your account",
    provideDetails: "Provide your details below",
    otpSent:'An OTP will be sent for confirmation',
    proceed:'PROCEED',
    otpVerification:'OTP Verification',
    enterCode:'Enter the code from sms we sent to ',
    resend:'RESEND',
    didntReceiveOtp:'Didn’t receive the OTP?',
    editProfile:'Edit Profile',
    editPicture:'Edit picture',
    userName:'Username',
    bio:'Bio',
    analyseProfile:'Let’s analyse your news interest profile',
    interestBased:'Your interests analysis based on your upvotes',
    today:'Today',
    dontHaveAcc:'Don’t have an account? ',
    sectionView:'Tap on a section to view',
    byPassOtp:'123456',
    top10Links: 'OUR TOP 10 LINKS',
    shareLink: 'Share a link',
    addComments: 'Add your comment',
    newPassword:'Enter new password',
    reenterPassword:'Re-enter new password',
    confirm:'Confirm',
    troubleLogin:'Trouble logging in?',
    enterDetails:"Enter your email, phone, or unique ID and we'll send you a link to get back into your account.",
    sendLoginLink:'Send Login Link',
    curatorAccess: "Curator Access",
    refferalOnly: "Referral invites only",
    audienceAccess: "Audience access",
    SignupMember: "Sign up and be a member",
}